#' Print a sdata object
#'
#' @description This functions prints the basic information of a data set generated by
#' Gen_data.
#' @param x Fitted '\code{sdata}' object.
#'
#' @param ... This argument is not used and listed for method consistency.
#'
#' @return
#' No return value.
#' @export
#' @method print sdata



print.sdata<-function(x,...){
  catln <- function (...)  base::cat(..., "\n", sep = "")
  print <- function (..., skip = 0, indent = 0) {
    output <- capture.output(base::print(...))
    if (skip > 0) output <- output[-seq_len(skip)]
    indent <- paste0(rep(" ", indent), collapse = "")
    cat(paste0(indent, output, "\n"), sep = "")
  }
  
  ## call
  catln("Call:")
  catln(" ", paste(deparse(x$call), sep = "\n", collapse = "\n"))
  
  catln("Subset:")
  catln(" Dim_of_Y: " , paste(c(length(x$Y),1),collapse = ' x '))
  catln(" Dim_of_X: " , paste(dim(x$X),collapse = ' x '))
  catln(" Correlation: " , x$correlation)
  catln(" Index_of_Casual_Featrues: " , paste(x$subset_true,collapse = ','))
  if(x$Ctg ==T){catln("Design matrix concludes categorical features" )}
  catln(" Model_Type: ", x$family)
  ## done
  invisible(x)
  
}